using ChessTrainer.Chess;
using ChessTrainer.Models;

namespace ChessTrainer.Services;

public sealed class TrainerCatalog
{
    public const int SourceChapterCount = 79;
    public const string StudyUrl = "https://lichess.org/study/TFiJoHCF";

    public IReadOnlyList<TrapExercise> Exercises { get; } =
    [
        Trap(1, "L’Hameçon français 🎣", "Facile", "Défense", "Défense française", "black",
            "r1bqkbnr/pp3ppp/2n1p3/2ppP3/3P4/2P2N2/PP3PPP/RNBQKB1R b KQkq - 1 1",
            M("c8d7", "…Fd7", "Prépare le piège en développant le fou."),
            M("f1b5", "Fb5", "Les Blancs attaquent."),
            M("c6e5", "…Cxe5", "Découvre l’attaque sur le fou."),
            M("b5d7", "Fxd7+", "Le fou prend avec échec."),
            M("e5d7", "…Cxd7", "Reprends et sauve le cavalier.")),

        Trap(2, "Le Franc-tireur du GDA 🔫", "Facile", "Attaque", "Gambit dame accepté", "white",
            "rnbqkbnr/ppp1pppp/8/8/2pP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 1",
            M("e2e3", "e3", "Ouvre la diagonale du fou."),
            M("b7b5", "…b5", "Les Noirs protègent leur pion."),
            M("a2a4", "a4", "Sape la chaîne de pions."),
            M("c7c6", "…c6", "Ils s’accrochent au pion."),
            M("a4b5", "axb5", "Ouvre la colonne a."),
            M("c6b5", "…cxb5", "La tour a8 devient vulnérable."),
            M("d1f3", "Df3", "Aligne la dame sur a8.")),

        Trap(3, "Festival de fourchettes ! 🍴", "Facile", "Défense", "Scandinave moderne", "black",
            "rnbqkbnr/ppp1pppp/8/3P4/8/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
            M("g8f6", "…Cf6", "Développe avec tempo."),
            M("b1c3", "Cc3", "Les Blancs défendent."),
            M("f6d5", "…Cxd5", "Récupère le pion."),
            M("c3d5", "Cxd5", "Échange du cavalier."),
            M("d8d5", "…Dxd5", "Reprends avec la dame."),
            M("g1f3", "Cf3", "Développement naturel."),
            M("b8c6", "…Cc6", "Développe le second cavalier."),
            M("d2d4", "d4", "Le centre blanc avance."),
            M("c6b4", "…Cb4", "Le cavalier entre en b4."),
            M("c2c3", "c3", "Il est chassé."),
            M("d5e4", "…De4+", "Premier échec et première fourchette."),
            M("f1e2", "Fe2", "Les Blancs parent l’échec."),
            M("b4c2", "…Cc2+", "Fourchette roi-tour décisive.")),

        Trap(4, "Briser le système de Londres ! 👮", "Intermédiaire", "Défense", "Système de Londres", "black",
            "rnbqkbnr/ppp1pppp/8/3p4/3P1B2/8/PPP1PPPP/RN1QKBNR b KQkq - 0 1",
            M("h7h5", "…h5", "Lance le pion h comme appât."),
            M("e2e3", "e3", "Le coup naturel attendu."),
            M("e7e5", "…e5", "Attaque le centre."),
            M("f4e5", "Fxe5", "Le fou prend le pion."),
            M("f7f6", "…f6", "Gagne un tempo sur le fou."),
            M("e5g3", "Fg3", "Le fou recule."),
            M("h5h4", "…h4", "Continue la chasse."),
            M("g3f4", "Ff4", "Dernière case apparente."),
            M("g7g5", "…g5", "Le fou est enfermé.")),

        Trap(5, "La Hongroise sournoise ! 🐍", "Intermédiaire", "Attaque", "Ouverture hongroise", "white",
            BoardState.StartFen,
            M("g2g3", "g3", "Prépare le fianchetto."),
            M("e7e5", "…e5", "Les Noirs prennent le centre."),
            M("f1g2", "Fg2", "Place le fou sur la grande diagonale."),
            M("d7d5", "…d5", "Le centre noir s’élargit."),
            M("c2c4", "c4", "Sape immédiatement d5."),
            M("c7c6", "…c6", "Les Noirs consolident."),
            M("d1a4", "Da4", "Cloue le pion c6."),
            M("c8d7", "…Fd7", "Une défense trop ambitieuse."),
            M("a4b3", "Db3", "Cible b7."),
            M("g8f6", "…Cf6", "Le pion reste offert."),
            M("b3b7", "Dxb7", "Prends le pion avec tempo."),
            M("b8a6", "…Ca6", "Le cavalier attaque la dame."),
            M("b7a6", "Dxa6", "Ramasse aussi le cavalier.")),

        Trap(6, "La Ponziani classique 🦄", "Intermédiaire", "Attaque", "Ponziani", "white",
            "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1",
            M("c2c3", "c3", "Prépare d4."),
            M("g8f6", "…Cf6", "Le cavalier attaque e4."),
            M("d2d4", "d4", "Occupe le centre."),
            M("f6e4", "…Cxe4", "Les Noirs deviennent gourmands."),
            M("d4d5", "d5", "Gagne de l’espace avec tempo."),
            M("c6e7", "…Ce7", "Le cavalier recule."),
            M("f3e5", "Cxe5", "Récupère le pion."),
            M("d7d6", "…d6", "L’erreur attendue."),
            M("f1b5", "Fb5+", "Cloue le roi."),
            M("c7c6", "…c6", "Réponse forcée."),
            M("d5c6", "dxc6", "Ouvre les lignes."),
            M("b7c6", "…bxc6", "Les Noirs reprennent."),
            M("e5c6", "Cxc6", "Le cavalier gagne encore un pion.")),

        Trap(7, "Stafford inversé ? ↩️🐴", "Difficile", "Attaque", "Défense Petrov", "white",
            "rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1",
            M("f1c4", "Fc4", "Refuse le Stafford et vise f7."),
            M("f6e4", "…Cxe4", "Les Noirs prennent le pion."),
            M("b1c3", "Cc3", "Propose le Stafford inversé."),
            M("e4c3", "…Cxc3", "Ils acceptent."),
            M("d2c3", "dxc3", "Reprends vers le centre."),
            M("d7d6", "…d6", "Le coup naturel attendu."),
            M("f3g5", "Cg5", "Double attaque sur f7."),
            M("c8e6", "…Fe6", "Les Noirs bloquent."),
            M("c4e6", "Fxe6", "Élimine le défenseur."),
            M("f7e6", "…fxe6", "La colonne et la diagonale s’ouvrent."),
            M("d1f3", "Df3", "Crée deux menaces."),
            M("d8f6", "…Df6", "La dame noire défend f7."),
            M("f3b7", "Dxb7", "Gagne la tour a8.")),

        Trap(8, "Sous-promotion dès l’ouverture ? 🤪", "Difficile", "Défense", "Gambit Blackmar-Diemer", "black",
            "rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq - 0 1",
            M("e7e5", "…e5", "Contre-attaque au centre."),
            M("d4e5", "dxe5", "Les Blancs acceptent."),
            M("d5d4", "…d4", "Crée un pion passé."),
            M("e2e3", "e3", "Ils offrent un pion."),
            M("f8b4", "…Fb4+", "Intercale un échec."),
            M("c1d2", "Fd2", "Le fou bloque."),
            M("d4e3", "…dxe3", "Ignore le fou et avance."),
            M("d2b4", "Fxb4", "Les Blancs prennent."),
            M("e3f2", "…exf2+", "Le pion arrive à une case de la promotion."),
            M("e1e2", "Re2", "Le roi s’écarte."),
            M("f2g1n", "…fxg1=C+", "Sous-promotion avec échec."),
            M("h1g1", "Txg1", "La tour capture le cavalier."),
            M("c8g4", "…Fg4+", "L’enfilade gagne la dame.")),

        Trap(9, "Développement à l’envers ? 🚨", "Difficile", "Défense", "Partie italienne", "black",
            "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 0 1",
            M("f7f5", "…f5", "Bouscule immédiatement e4."),
            M("e4f5", "exf5", "Les Blancs prennent."),
            M("e5e4", "…e4", "Chasse le cavalier."),
            M("f3g1", "Cg1", "Le cavalier se redéveloppe à l’envers."),
            M("d7d5", "…d5", "Ouvre le centre."),
            M("c4b5", "Fb5", "Le fou cherche l’échec."),
            M("d8g5", "…Dg5", "Fourchette g2/f5."),
            M("b5c6", "Fxc6+", "Le fou prend avec échec."),
            M("b7c6", "…bxc6", "Reprends le fou."),
            M("g2g3", "g3", "La dame est attaquée."),
            M("g5f5", "…Dxf5", "Récupère le pion avec avantage.")),

        Trap(10, "L’Anti-Anti-Alien 🚫🚫🛸", "Terrifiant", "Attaque", "Caro-Kann · Gambit Alien", "white",
            "rnbqkb1r/pp2pppp/2p2n2/8/3PN3/8/PPP2PPP/R1BQKBNR w KQkq - 0 1",
            M("e4g5", "Cg5", "Commence le gambit Alien."),
            M("h7h6", "…h6", "Le cavalier est chassé."),
            M("g5f7", "Cxf7", "Sacrifie sur f7."),
            M("e8f7", "…Rxf7", "Le roi accepte."),
            M("g1f3", "Cf3", "Développe avec tempo à venir."),
            M("c6c5", "…c5", "L’Anti-Alien de Stockfish."),
            M("d4d5", "d5", "Lance l’Anti-Anti-Alien."),
            M("d8d5", "…Dxd5", "La dame s’aligne avec le roi."),
            M("f1c4", "Fc4", "Sacrifie le fou pour attirer la dame."),
            M("d5c4", "…Dxc4", "Les Noirs mordent."),
            M("f3e5", "Ce5+", "Fourchette roi-dame.")),

        Trap(11, "Pulvériser la Philidor ! 🔨", "Terrifiant", "Attaque", "Défense Philidor", "white",
            "rnbqkbnr/ppp2ppp/3p4/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1",
            M("f1c4", "Fc4", "Vise f7."),
            M("h7h6", "…h6", "Un tempo lent."),
            M("d2d4", "d4", "Frappe le centre."),
            M("e5d4", "…exd4", "Les Noirs prennent."),
            M("c2c3", "c3", "Sacrifie un second pion."),
            M("d4c3", "…dxc3", "Ils acceptent encore."),
            M("c4f7", "Fxf7+", "Premier sacrifice."),
            M("e8f7", "…Rxf7", "Le roi s’expose."),
            M("f3e5", "Ce5+", "Second sacrifice, la dame est intouchable."),
            M("f7e8", "…Re8", "Le roi recule."),
            M("d1h5", "Dh5+", "Lance le réseau de mat."),
            M("g7g6", "…g6", "Seule façon de retarder."),
            M("h5g6", "Dxg6+", "Le roi reste exposé."),
            M("e8e7", "…Re7", "Dernière fuite."),
            M("g6f7", "Df7#", "Mat au huitième coup.")),

        Trap(12, "Double sacrifice !!!", "Terrifiant", "Attaque", "Caro-Kann", "white",
            "rnbqkbnr/pp1ppppp/2p5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1",
            M("g1f3", "Cf3", "Développe simplement."),
            M("d7d5", "…d5", "Le centre noir répond."),
            M("d2d3", "d3", "Tends le piège."),
            M("d5e4", "…dxe4", "Les Noirs prennent."),
            M("f3g5", "Cg5", "Vise f7."),
            M("e4d3", "…exd3", "Ils prennent encore."),
            M("f1d3", "Fxd3", "Reprends et aligne le fou."),
            M("g8f6", "…Cf6", "Développement naturel."),
            M("g5f7", "Cxf7", "Premier sacrifice."),
            M("e8f7", "…Rxf7", "Le roi accepte."),
            M("d3g6", "Fg6+", "Deuxième sacrifice."),
            M("h7g6", "…hxg6", "La colonne s’ouvre."),
            M("d1d8", "Dxd8", "La dame noire tombe.")),

        Trap(13, "Le Londres grillé 🍳", "Ultra-rapide", "Défense", "Système de Londres", "black",
            "rnbqkbnr/ppp1pppp/8/3p4/3P1B2/8/PPP1PPPP/RN1QKBNR b KQkq - 0 1",
            M("c8g4", "…Fg4", "Cloue le pion e2 à la dame."),
            M("e2e3", "e3?", "Le pré-coup typique du système de Londres."),
            M("g4d1", "…Fxd1", "Ramasse la dame.")),

        Trap(14, "Le casse ! 🥷", "Ultra-rapide", "Attaque", "Défense moderne", "white",
            "rnbqkbnr/pppppp1p/6p1/8/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 1",
            M("c1h6", "Fh6", "Place le fou devant le fianchetto."),
            M("f8g7", "…Fg7?", "Le développement automatique attendu."),
            M("h6g7", "Fxg7", "Vole le fou et la tour suivra.")),

        Trap(15, "Le cavalier chevaleresque ! ⚜️", "Variante", "Attaque", "Échecs atomiques", "white",
            BoardState.StartFen,
            M("g1f3", "Cf3", "Développe le cavalier."),
            M("f7f6", "…f6", "Le roi noir s’affaiblit."),
            M("e2e3", "e3", "Prépare la dame."),
            M("c7c5", "…c5", "Un coup sans rapport avec l’aile roi."),
            M("f3e5", "Ce5!", "Sacrifie le cavalier atomique."),
            M("f6e5", "…fxe5", "Les Noirs acceptent."),
            M("d1h5", "Dh5+", "Attaque le roi."),
            M("g7g6", "…g6", "La dame est chassée."),
            M("h5d5", "Dd5", "Fourchette f7/d7."),
            M("d7d6", "…d6", "Les Noirs bloquent."),
            M("d5f7", "Df7+", "Poursuis le roi."),
            M("e8d7", "…Rd7", "Le roi fuit."),
            M("f7e7", "Dxe7#", "Explosion finale.")),

        Trap(16, "Mat en 2,5 coups !", "Variante", "Attaque", "Roi de la colline", "white",
            BoardState.StartFen,
            M("e2e3", "e3", "Libère la dame."),
            M("e7e5", "…e5", "Les Noirs occupent le centre."),
            M("d1h5", "Dh5", "Tends le piège sur e5."),
            M("e8e7", "…Re7?", "Le roi marche vers la colline."),
            M("h5e5", "Dxe5#", "Mat en deux coups et demi.")),

        Trap(17, "Leçon à une victime sans méfiance 🗡️", "Variante", "Attaque", "Échecs 960", "white",
            "qbbnnkrn/pppppppp/8/8/8/8/PPPPPPPP/QBBNNKRN w - - 0 1",
            M("c2c3", "c3", "Libère la diagonale du fou."),
            M("e7e5", "…e5?", "Les Noirs ignorent h7."),
            M("b1h7", "Fxh7", "Prends le pion et enferme la tour.")),

        Trap(18, "Le Mat du sot 🤡", "Facile", "Attaque", "Ouverture ouverte", "white",
            "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
            M("e2e4", "e4", "Tends le piège en développant avec tempo."),
            M("f7f6", "…f6", "La réplique adverse attendue."),
            M("d2d4", "d4", "Tends le piège en développant avec tempo."),
            M("g7g5", "…g5", "La réplique adverse attendue."),
            M("d1h5", "Dh5#", "Mat imparable !")),

        Trap(19, "Le Coup du berger 🐑", "Facile", "Attaque", "Ouverture ouverte", "white",
            "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
            M("e2e4", "e4", "Tends le piège en développant avec tempo."),
            M("e7e5", "…e5", "La réplique adverse attendue."),
            M("d1h5", "Dh5", "Tends le piège en développant avec tempo."),
            M("b8c6", "…Cc6", "La réplique adverse attendue."),
            M("f1c4", "Fc4", "Tends le piège en développant avec tempo."),
            M("g8f6", "…Cf6", "La réplique adverse attendue."),
            M("h5f7", "Dxf7#", "Mat imparable !")),

        Trap(20, "Le Piège de Legal ⚔️", "Intermédiaire", "Attaque", "Défense Philidor", "white",
            "rn1qkbnr/ppp2p1p/3p2p1/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5",
            M("f3e5", "Cxe5", "Prends la pièce et lance la combinaison."),
            M("g4d1", "…Fxd1", "L'adversaire mord à l'hameçon et capture !"),
            M("c4f7", "Fxf7+", "Prends la pièce et lance la combinaison."),
            M("e8e7", "…Re7", "La réplique adverse attendue."),
            M("c3d5", "Cd5#", "Mat imparable !")),

        Trap(21, "Le Piège de l'Éléphant 🐘", "Intermédiaire", "Défense", "Gambit dame", "black",
            "r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6",
            M("f6d5", "…Cxd5", "Prends la pièce et lance la combinaison."),
            M("g5d8", "Fxd8", "L'adversaire mord à l'hameçon et capture !"),
            M("f8b4", "…Fb4+", "Intercale un échec décisif."),
            M("d1d2", "Dd2", "La réplique adverse attendue."),
            M("b4d2", "…Fxd2+", "Prends la pièce et lance la combinaison."),
            M("e1d2", "Rxd2", "L'adversaire mord à l'hameçon et capture !"),
            M("e8d8", "…Rxd8", "Capture la pièce sans défense !")),

        Trap(22, "Le Piège de Blackburne-Shilling 💰", "Facile", "Défense", "Partie italienne", "black",
            "r1b1kbnr/pppp1Npp/8/6q1/2BnP3/8/PPPP1PPP/RNBQK2R b KQkq - 0 5",
            M("g5g2", "…Dxg2", "Prends la pièce et lance la combinaison."),
            M("h1f1", "Tf1", "La réplique adverse attendue."),
            M("g2e4", "…Dxe4+", "Prends la pièce et lance la combinaison."),
            M("c4e2", "Fe2", "La réplique adverse attendue."),
            M("d4f3", "…Cf3#", "Mat imparable !")),

        Trap(23, "La Canne à pêche 🎣", "Intermédiaire", "Défense", "Partie espagnole", "black",
            "r1bqkb1r/pppp1ppp/2n5/1B2p3/4P1n1/5N1P/PPPP1PP1/RNBQ1RK1 b kq - 0 5",
            M("h7h5", "…h5", "Tends le piège en développant avec tempo."),
            M("h3g4", "hxg4", "L'adversaire mord à l'hameçon et capture !"),
            M("h5g4", "…hxg4", "Prends la pièce et lance la combinaison."),
            M("f3e1", "Ce1", "La réplique adverse attendue."),
            M("d8h4", "…Dh4", "Tends le piège en développant avec tempo."),
            M("g2g3", "g3", "La réplique adverse attendue."),
            M("h4h1", "…Dh1#", "Mat imparable !")),

        Trap(24, "L'Arche de Noé 🚢", "Intermédiaire", "Défense", "Partie espagnole", "black",
            "r1bqkbnr/2p2ppp/p2p4/1p6/3QP3/1B6/PPP2PPP/RNB1K2R b KQkq - 0 8",
            M("c7c5", "…c5", "Tends le piège en développant avec tempo."),
            M("d4d5", "Dd5", "La réplique adverse attendue."),
            M("c8e6", "…Fe6", "Tends le piège en développant avec tempo."),
            M("d5c6", "Dc6+", "Échec intermédiaire adverse."),
            M("e6d7", "…Fd7", "Tends le piège en développant avec tempo."),
            M("c6d5", "Dd5", "La réplique adverse attendue."),
            M("c5c4", "…c4", "Porte le coup de grâce tactique.")),

        Trap(25, "Le Piège Magnus Smith 💥", "Difficile", "Attaque", "Défense sicilienne", "white",
            "r1bqkb1r/pp2pp1p/2np1np1/8/2BNP3/2N5/PPP2PPP/R1BQK2R w KQkq - 0 7",
            M("d4c6", "Cxc6", "Prends la pièce et lance la combinaison."),
            M("b7c6", "…bxc6", "L'adversaire mord à l'hameçon et capture !"),
            M("e4e5", "e5", "Tends le piège en développant avec tempo."),
            M("d6e5", "…dxe5", "L'adversaire mord à l'hameçon et capture !"),
            M("c4f7", "Fxf7+", "Prends la pièce et lance la combinaison."),
            M("e8f7", "…Rxf7", "L'adversaire mord à l'hameçon et capture !"),
            M("d1d8", "Dxd8", "Capture la pièce sans défense !")),

        Trap(26, "Le Piège Sibérien ❄️", "Intermédiaire", "Attaque", "Défense sicilienne", "white",
            "r1b1kb1r/ppqp1ppp/2n1pn2/8/2B1P3/2N2N2/PP3PPP/R1BQ1RK1 w kq - 4 8",
            M("d1e2", "De2", "Tends le piège en développant avec tempo."),
            M("f6g4", "…Cg4", "La réplique adverse attendue."),
            M("h2h3", "h3", "Tends le piège en développant avec tempo."),
            M("c6d4", "…Cd4", "La réplique adverse attendue."),
            M("h3g4", "hxg4", "Prends la pièce et lance la combinaison."),
            M("d4e2", "…Cxe2+", "L'adversaire mord à l'hameçon et capture !"),
            M("c3e2", "Cxe2", "Capture la pièce sans défense !")),

        Trap(27, "Le Piège de Lasker 👑", "Difficile", "Défense", "Gambit dame", "black",
            "rnbqk1nr/ppp2ppp/8/4P3/1BP5/4p3/PP3PPP/RN1QKBNR b KQkq - 0 6",
            M("e3f2", "…exf2+", "Prends la pièce et lance la combinaison."),
            M("e1e2", "Re2", "La réplique adverse attendue."),
            M("f2g1n", "…fxg1=C+", "Prends la pièce et lance la combinaison."),
            M("h1g1", "Txg1", "L'adversaire mord à l'hameçon et capture !"),
            M("c8g4", "…Fg4+", "Intercale un échec décisif."),
            M("e2f2", "Rf2", "La réplique adverse attendue."),
            M("d8d1", "…Dxd1", "Capture la pièce sans défense !")),

        Trap(28, "Le Piège de Kieninger ♟️", "Intermédiaire", "Défense", "Gambit de Budapest", "black",
            "r1bqkb1r/pppp1ppp/2n5/4P3/2P2Bn1/5N2/PP2PPPP/RN1QKB1R b KQkq - 4 5",
            M("f8b4", "…Fb4+", "Intercale un échec décisif."),
            M("b1d2", "Cbd2", "La réplique adverse attendue."),
            M("d8e7", "…De7", "Tends le piège en développant avec tempo."),
            M("a2a3", "a3", "La réplique adverse attendue."),
            M("g4e5", "…Cgxe5", "Prends la pièce et lance la combinaison."),
            M("a3b4", "axb4", "L'adversaire mord à l'hameçon et capture !"),
            M("e5d3", "…Cd3#", "Mat imparable !")),

        Trap(29, "Le Piège Fajarowicz ⚡", "Difficile", "Défense", "Gambit de Budapest", "black",
            "rnbqkb1r/ppp2ppp/3P4/8/2P1n3/5N2/PP2PPPP/RNBQKB1R b KQkq - 0 5",
            M("f8d6", "…Fxd6", "Prends la pièce et lance la combinaison."),
            M("g2g3", "g3", "La réplique adverse attendue."),
            M("e4f2", "…Cxf2", "Prends la pièce et lance la combinaison."),
            M("e1f2", "Rxf2", "L'adversaire mord à l'hameçon et capture !"),
            M("d6g3", "…Fxg3+", "Prends la pièce et lance la combinaison."),
            M("h2g3", "hxg3", "L'adversaire mord à l'hameçon et capture !"),
            M("d8d1", "…Dxd1", "Capture la pièce sans défense !")),

        Trap(30, "Le Piège de Würzburger 🏰", "Difficile", "Défense", "Partie viennoise", "black",
            "rnb1kb1r/ppp2ppp/8/3NP2q/8/3P1Nn1/PPP4P/R1BQKB1R b KQkq - 0 8",
            M("c8g4", "…Fg4", "Tends le piège en développant avec tempo."),
            M("d5f4", "Cf4", "La réplique adverse attendue."),
            M("g4f3", "…Fxf3", "Prends la pièce et lance la combinaison."),
            M("f4h5", "Cxh5", "L'adversaire mord à l'hameçon et capture !"),
            M("f3d1", "…Fxd1", "Prends la pièce et lance la combinaison."),
            M("h2g3", "hxg3", "L'adversaire mord à l'hameçon et capture !"),
            M("d1c2", "…Fxc2", "Capture la pièce sans défense !")),

        Trap(31, "Le Gambit Englund foudroyant ⚡", "Facile", "Défense", "Gambit Englund", "black",
            "r1b1kbnr/pppp1ppp/2n5/4P3/1q6/5N2/PPPBPPPP/RN1QKB1R b KQkq - 6 5",
            M("b4b2", "…Dxb2", "Prends la pièce et lance la combinaison."),
            M("d2c3", "Fc3", "La réplique adverse attendue."),
            M("f8b4", "…Fb4", "Tends le piège en développant avec tempo."),
            M("d1d2", "Dd2", "La réplique adverse attendue."),
            M("b4c3", "…Fxc3", "Prends la pièce et lance la combinaison."),
            M("d2c3", "Dxc3", "L'adversaire mord à l'hameçon et capture !"),
            M("b2c1", "…Dc1#", "Mat imparable !")),

        Trap(32, "Le Piège du Gambit Stafford 🐴", "Facile", "Défense", "Défense Petrov", "black",
            "r1bqkb1r/ppp2ppp/2p2n2/8/4P3/3P4/PPP2PPP/RNBQKB1R b KQkq - 0 5",
            M("f8c5", "…Fc5", "Tends le piège en développant avec tempo."),
            M("c1g5", "Fg5", "La réplique adverse attendue."),
            M("f6e4", "…Cxe4", "Prends la pièce et lance la combinaison."),
            M("g5d8", "Fxd8", "L'adversaire mord à l'hameçon et capture !"),
            M("c5f2", "…Fxf2+", "Prends la pièce et lance la combinaison."),
            M("e1e2", "Re2", "La réplique adverse attendue."),
            M("c8g4", "…Fg4#", "Mat imparable !")),

        Trap(33, "Le Gambit Tennison intercontinental 🚀", "Intermédiaire", "Attaque", "Gambit Tennison", "white",
            "rnbqkb1r/ppp1pppp/5n2/6N1/8/3p4/PPP2PPP/RNBQKB1R w KQkq - 0 5",
            M("f1d3", "Fxd3", "Prends la pièce et lance la combinaison."),
            M("h7h6", "…h6", "La réplique adverse attendue."),
            M("g5f7", "Cxf7", "Prends la pièce et lance la combinaison."),
            M("e8f7", "…Rxf7", "L'adversaire mord à l'hameçon et capture !"),
            M("d3g6", "Fg6+", "Intercale un échec décisif."),
            M("f7g6", "…Rxg6", "L'adversaire mord à l'hameçon et capture !"),
            M("d1d8", "Dxd8", "Capture la pièce sans défense !")),

        Trap(34, "Le Piège de Halosar ⚔️", "Difficile", "Attaque", "Ouverture ouverte", "white",
            "rnb1kb1r/ppp1pppp/5n2/8/3q4/2N2Q2/PPP3PP/R1B1KBNR w KQkq - 0 6",
            M("c1e3", "Fe3", "Tends le piège en développant avec tempo."),
            M("d4b4", "…Db4", "La réplique adverse attendue."),
            M("e1c1", "O-O-O", "Tends le piège en développant avec tempo."),
            M("c8g4", "…Fg4", "La réplique adverse attendue."),
            M("c3b5", "Cb5", "Tends le piège en développant avec tempo."),
            M("g4f3", "…Fxf3", "L'adversaire mord à l'hameçon et capture !"),
            M("b5c7", "Cxc7#", "Mat imparable !")),

        Trap(35, "Le Piège de Rubinstein 💎", "Difficile", "Attaque", "Gambit dame", "white",
            "r1bqr1k1/1p1nbppp/p1p2n2/3p2B1/3P4/2NBPN2/PPQ2PPP/2R1K2R w K - 0 11",
            M("e1g1", "O-O", "Tends le piège en développant avec tempo."),
            M("f6e4", "…Ce4", "La réplique adverse attendue."),
            M("g5f4", "Ff4", "Tends le piège en développant avec tempo."),
            M("f7f5", "…f5", "La réplique adverse attendue."),
            M("c3d5", "Cxd5", "Prends la pièce et lance la combinaison."),
            M("c6d5", "…cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("f4c7", "Fc7", "Porte le coup de grâce tactique.")),

        Trap(36, "Le Piège de Monticelli 🦅", "Difficile", "Attaque", "Défense bogo-indienne", "white",
            "rn1q1rk1/pbpp1ppp/1p2p3/8/2PP4/2n2NP1/PPQ1PPBP/R3K2R w KQ - 0 10",
            M("f3g5", "Cg5", "Tends le piège en développant avec tempo."),
            M("d8g5", "…Dxg5", "L'adversaire mord à l'hameçon et capture !"),
            M("g2b7", "Fxb7", "Prends la pièce et lance la combinaison."),
            M("b8c6", "…Cc6", "La réplique adverse attendue."),
            M("b7a8", "Fxa8", "Prends la pièce et lance la combinaison."),
            M("f8a8", "…Txa8", "L'adversaire mord à l'hameçon et capture !"),
            M("c2c3", "Dxc3", "Capture la pièce sans défense !")),

        Trap(37, "Le Piège de Harksen 🎯", "Intermédiaire", "Attaque", "Défense scandinave", "white",
            "rn1qkb1r/pp3ppp/2p1pn2/3N1b2/2BP4/5N2/PPPB1PPP/R2QK2R w KQkq - 2 9",
            M("d5f6", "Cxf6+", "Prends la pièce et lance la combinaison."),
            M("d8f6", "…Dxf6", "L'adversaire mord à l'hameçon et capture !"),
            M("d1e2", "De2", "Tends le piège en développant avec tempo."),
            M("f5c2", "…Fxc2", "L'adversaire mord à l'hameçon et capture !"),
            M("d2g5", "Fg5", "Tends le piège en développant avec tempo."),
            M("f6g6", "…Dg6", "La réplique adverse attendue."),
            M("e1g1", "O-O", "Porte le coup de grâce tactique.")),

        Trap(38, "Le Piège de Marshall 🛡️", "Intermédiaire", "Défense", "Défense Petrov", "black",
            "rnbq1rk1/ppp2ppp/3b4/3p4/2PPn3/3B1N2/PP3PPP/RNBQ1RK1 b - - 0 8",
            M("c8g4", "…Fg4", "Tends le piège en développant avec tempo."),
            M("c4d5", "cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("f7f5", "…f5", "Tends le piège en développant avec tempo."),
            M("f1e1", "Te1", "La réplique adverse attendue."),
            M("d6h2", "…Fxh2+", "Prends la pièce et lance la combinaison."),
            M("g1h2", "Rxh2", "L'adversaire mord à l'hameçon et capture !"),
            M("e4f2", "…Cxf2", "Capture la pièce sans défense !")),

        Trap(39, "L'Embuscade de Réti 🕸️", "Intermédiaire", "Défense", "Ouverture Réti", "black",
            "rn1qkbnr/1ppb2pp/5p2/pPP1p3/Q2p4/4PN2/P2P1PPP/RNB1KB1R b KQkq - 0 7",
            M("f8c5", "…Fxc5", "Prends la pièce et lance la combinaison."),
            M("e3d4", "exd4", "L'adversaire mord à l'hameçon et capture !"),
            M("e5d4", "…exd4", "Prends la pièce et lance la combinaison."),
            M("f3d4", "Cxd4", "L'adversaire mord à l'hameçon et capture !"),
            M("d8e7", "…De7+", "Intercale un échec décisif."),
            M("e1d1", "Rd1", "La réplique adverse attendue."),
            M("e7e4", "…De4", "Porte le coup de grâce tactique.")),

        Trap(40, "L'Attaque du foie fessé 🍗", "Facile", "Attaque", "Partie italienne", "white",
            "r1bqkb1r/ppp2ppp/2n2n2/3pp1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 5",
            M("e4d5", "exd5", "Prends la pièce et lance la combinaison."),
            M("f6d5", "…Cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("g5f7", "Cxf7", "Prends la pièce et lance la combinaison."),
            M("e8f7", "…Rxf7", "L'adversaire mord à l'hameçon et capture !"),
            M("d1f3", "Df3+", "Intercale un échec décisif."),
            M("f7e6", "…Re6", "La réplique adverse attendue."),
            M("b1c3", "Cc3", "Porte le coup de grâce tactique.")),

        Trap(41, "Mat à l'étouffée Caro-Kann 💨", "Facile", "Attaque", "Défense Caro-Kann", "white",
            "rnbqkbnr/pp2pppp/2p5/8/4p3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 0 4",
            M("c3e4", "Cxe4", "Prends la pièce et lance la combinaison."),
            M("g8f6", "…Cf6", "La réplique adverse attendue."),
            M("d1e2", "De2", "Tends le piège en développant avec tempo."),
            M("b8d7", "…Cbd7", "La réplique adverse attendue."),
            M("e4d6", "Cd6#", "Mat imparable !")),

        Trap(42, "Piège en Défense française 🥐", "Intermédiaire", "Défense", "Défense française", "black",
            "rnbq1rk1/ppp1bppp/5n2/3p2B1/2PP4/2N2N2/PP3PPP/R2QKB1R b KQ - 6 7",
            M("c7c6", "…c6", "Tends le piège en développant avec tempo."),
            M("f1d3", "Fd3", "La réplique adverse attendue."),
            M("d5c4", "…dxc4", "Prends la pièce et lance la combinaison."),
            M("d3c4", "Fxc4", "L'adversaire mord à l'hameçon et capture !"),
            M("b8d7", "…Cbd7", "Tends le piège en développant avec tempo."),
            M("e1g1", "O-O", "La réplique adverse attendue."),
            M("d7b6", "…Cb6", "Porte le coup de grâce tactique.")),

        Trap(43, "Le Gambit écossais tranchant 🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Facile", "Attaque", "Partie italienne", "white",
            "r1bqkb1r/pppp1ppp/2n2n2/8/2BpP3/5N2/PPP2PPP/RNBQK2R w KQkq - 2 5",
            M("e1g1", "O-O", "Tends le piège en développant avec tempo."),
            M("f6e4", "…Cxe4", "L'adversaire mord à l'hameçon et capture !"),
            M("f1e1", "Te1", "Tends le piège en développant avec tempo."),
            M("d7d5", "…d5", "La réplique adverse attendue."),
            M("c4d5", "Fxd5", "Prends la pièce et lance la combinaison."),
            M("d8d5", "…Dxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("b1c3", "Cc3", "Porte le coup de grâce tactique.")),

        Trap(44, "L'Étouffée anglaise ☕", "Intermédiaire", "Attaque", "Ouverture anglaise", "white",
            "r1bqk2r/pppp1ppp/2n5/3P4/1b2p3/5NP1/PP1PPP1P/R1BQKB1R w KQkq - 0 7",
            M("d5c6", "dxc6", "Prends la pièce et lance la combinaison."),
            M("e4f3", "…exf3", "L'adversaire mord à l'hameçon et capture !"),
            M("d1b3", "Db3", "Tends le piège en développant avec tempo."),
            M("f3e2", "…fxe2", "L'adversaire mord à l'hameçon et capture !"),
            M("f1e2", "Fxe2", "Prends la pièce et lance la combinaison."),
            M("d7c6", "…dxc6", "L'adversaire mord à l'hameçon et capture !"),
            M("b3b4", "Dxb4", "Capture la pièce sans défense !")),

        Trap(45, "Le Cavalier piégé en Alapine 🐴", "Intermédiaire", "Attaque", "Défense sicilienne", "white",
            "r3kbnr/pp2pppp/8/1N6/8/5P2/PP3P1P/n1BK1B1R w kq - 0 12",
            M("b5c7", "Cc7+", "Intercale un échec décisif."),
            M("e8d7", "…Rd7", "La réplique adverse attendue."),
            M("c7a8", "Cxa8", "Prends la pièce et lance la combinaison."),
            M("d7c8", "…Rc8", "La réplique adverse attendue."),
            M("c1f4", "Ff4", "Tends le piège en développant avec tempo."),
            M("b7b6", "…b6", "La réplique adverse attendue."),
            M("a8c7", "Cc7", "Porte le coup de grâce tactique.")),

        Trap(46, "La Réfutation du Gambit Dame ♟️", "Intermédiaire", "Défense", "Défense slave", "black",
            "rnbqk2r/5ppp/p1pbpn2/1p6/3PP3/2NB1N2/PP3PPP/R1BQK2R b KQkq - 0 9",
            M("c6c5", "…c5", "Tends le piège en développant avec tempo."),
            M("e4e5", "e5", "La réplique adverse attendue."),
            M("c5d4", "…cxd4", "Prends la pièce et lance la combinaison."),
            M("c3b5", "Cxb5", "L'adversaire mord à l'hameçon et capture !"),
            M("a6b5", "…axb5", "Prends la pièce et lance la combinaison."),
            M("d3b5", "Fxb5+", "L'adversaire mord à l'hameçon et capture !"),
            M("c8d7", "…Fd7", "Porte le coup de grâce tactique.")),

        Trap(47, "Piège en Partie du pion dame 🏛️", "Intermédiaire", "Attaque", "Partie du pion dame", "white",
            "r2q1rk1/pb3ppp/1p1bpn2/2ppNn2/3P1P2/2PBPQB1/PP1N2PP/R3K2R w KQ - 3 12",
            M("g3f2", "Ff2", "Tends le piège en développant avec tempo."),
            M("d6e7", "…Fe7", "La réplique adverse attendue."),
            M("g2g4", "g4", "Tends le piège en développant avec tempo."),
            M("f5d6", "…Cd6", "La réplique adverse attendue."),
            M("g4g5", "g5", "Tends le piège en développant avec tempo."),
            M("f6e4", "…Cfe4", "La réplique adverse attendue."),
            M("f3h3", "Dh3", "Porte le coup de grâce tactique.")),

        Trap(48, "La Dame piégée en Scandinave 👸", "Intermédiaire", "Attaque", "Défense scandinave", "white",
            "rn1qk2r/pp3ppp/2p1p3/8/1b1Pn3/4BQ1P/PPP2PP1/2KR1B1R w kq - 0 11",
            M("f3e4", "Dxe4", "Prends la pièce et lance la combinaison."),
            M("d8d5", "…Dd5", "La réplique adverse attendue."),
            M("e4d5", "Dxd5", "Prends la pièce et lance la combinaison."),
            M("c6d5", "…cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("c2c4", "c4", "Tends le piège en développant avec tempo."),
            M("d5c4", "…dxc4", "L'adversaire mord à l'hameçon et capture !"),
            M("f1c4", "Fxc4", "Capture la pièce sans défense !")),

        Trap(49, "Le Piège Busch-Gass 🧨", "Difficile", "Défense", "Ouverture ouverte", "black",
            "r1b1k1nr/ppp2ppp/2p5/2b5/4P2q/2P2Q2/PP1P1PPP/RNB1KB1R b KQkq - 2 6",
            M("g8f6", "…Cf6", "Tends le piège en développant avec tempo."),
            M("d2d4", "d4", "La réplique adverse attendue."),
            M("c8g4", "…Fg4", "Tends le piège en développant avec tempo."),
            M("f3e3", "De3", "La réplique adverse attendue."),
            M("e8c8", "…O-O-O", "Tends le piège en développant avec tempo."),
            M("d4c5", "dxc5", "L'adversaire mord à l'hameçon et capture !"),
            M("d8d1", "…Td1#", "Mat imparable !")),

        Trap(50, "Piège en Partie italienne ⚡", "Intermédiaire", "Défense", "Partie italienne", "black",
            "r2Nk2r/ppp5/2np1n2/2b1p3/2B1P1b1/3P2p1/PPPQ1PPP/RN3RK1 b kq - 2 12",
            M("c6d4", "…Cd4", "Tends le piège en développant avec tempo."),
            M("h2h3", "h3", "La réplique adverse attendue."),
            M("d4e2", "…Ce2+", "Intercale un échec décisif."),
            M("g1h1", "Rh1", "La réplique adverse attendue."),
            M("h8h3", "…Txh3+", "Prends la pièce et lance la combinaison."),
            M("g2h3", "gxh3", "L'adversaire mord à l'hameçon et capture !"),
            M("g4f3", "…Ff3#", "Mat imparable !")),

        Trap(51, "Piège en Gambit dame ⚡", "Intermédiaire", "Attaque", "Gambit dame", "white",
            "rnbqkbnr/ppp2ppp/8/8/2pp4/4PN2/PP3PPP/RNBQKB1R w KQkq - 0 5",
            M("f1c4", "Fxc4", "Prends la pièce et lance la combinaison."),
            M("g8f6", "…Cf6", "La réplique adverse attendue."),
            M("d1b3", "Db3", "Tends le piège en développant avec tempo."),
            M("d8e7", "…De7", "La réplique adverse attendue."),
            M("e1g1", "O-O", "Tends le piège en développant avec tempo."),
            M("d4d3", "…d3", "La réplique adverse attendue."),
            M("f3g5", "Cg5", "Porte le coup de grâce tactique.")),

        Trap(52, "Piège en Défense Caro-Kann ⚡", "Intermédiaire", "Attaque", "Défense Caro-Kann", "white",
            "rnbqkbnr/pp2pppp/2p5/6N1/8/3p4/PPP2PPP/RNBQKB1R w KQkq - 0 5",
            M("f1d3", "Fxd3", "Prends la pièce et lance la combinaison."),
            M("g8f6", "…Cf6", "La réplique adverse attendue."),
            M("g5f7", "Cxf7", "Prends la pièce et lance la combinaison."),
            M("e8f7", "…Rxf7", "L'adversaire mord à l'hameçon et capture !"),
            M("d3g6", "Fg6+", "Échec et gain matériel décisif.")),

        Trap(53, "Piège en Partie italienne ⚡", "Intermédiaire", "Attaque", "Partie italienne", "white",
            "r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 2 5",
            M("h2h3", "h3", "Tends le piège en développant avec tempo."),
            M("g4h5", "…Fh5", "La réplique adverse attendue."),
            M("f3e5", "Cxe5", "Prends la pièce et lance la combinaison."),
            M("h5d1", "…Fxd1", "L'adversaire mord à l'hameçon et capture !"),
            M("c4f7", "Fxf7+", "Prends la pièce et lance la combinaison."),
            M("e8e7", "…Re7", "La réplique adverse attendue."),
            M("c3d5", "Cd5#", "Mat imparable !")),

        Trap(54, "Piège en Défense moderne ⚡", "Intermédiaire", "Attaque", "Défense moderne", "white",
            "r1bqk1nr/pppnppbp/3p2p1/8/2BPP3/5N2/PPP2PPP/RNBQK2R w KQkq - 2 5",
            M("c4f7", "Fxf7+", "Prends la pièce et lance la combinaison."),
            M("e8f7", "…Rxf7", "L'adversaire mord à l'hameçon et capture !"),
            M("f3g5", "Cg5+", "Intercale un échec décisif."),
            M("f7e8", "…Re8", "La réplique adverse attendue."),
            M("g5e6", "Ce6", "Porte le coup de grâce tactique.")),

        Trap(55, "Piège en Défense sicilienne ⚡", "Intermédiaire", "Attaque", "Défense sicilienne", "white",
            "r1bqkb1r/pp3ppp/8/3n4/2Bp4/8/PPPP1PPP/R1BQ1RK1 w kq - 0 10",
            M("d1h5", "Dh5", "Tends le piège en développant avec tempo."),
            M("c8e6", "…Fe6", "La réplique adverse attendue."),
            M("f1e1", "Te1", "Tends le piège en développant avec tempo."),
            M("f8e7", "…Fe7", "La réplique adverse attendue."),
            M("e1e6", "Txe6", "Prends la pièce et lance la combinaison."),
            M("e8g8", "…O-O", "La réplique adverse attendue."),
            M("e6e1", "Te1", "Porte le coup de grâce tactique.")),

        Trap(56, "Piège en Défense Caro-Kann ⚡", "Intermédiaire", "Défense", "Défense Caro-Kann", "black",
            "rnbqkb1r/pp2ppp1/2p5/4B3/3P4/6p1/PPP2PPP/R2QKBNR b KQkq - 1 8",
            M("h8h2", "…Txh2", "Prends la pièce et lance la combinaison."),
            M("h1h2", "Txh2", "L'adversaire mord à l'hameçon et capture !"),
            M("d8a5", "…Da5+", "Intercale un échec décisif."),
            M("c2c3", "c3", "La réplique adverse attendue."),
            M("a5e5", "…Dxe5+", "Prends la pièce et lance la combinaison."),
            M("d4e5", "dxe5", "L'adversaire mord à l'hameçon et capture !"),
            M("g3h2", "…gxh2", "Capture la pièce sans défense !")),

        Trap(57, "Piège en Défense scandinave ⚡", "Intermédiaire", "Attaque", "Défense scandinave", "white",
            "r2q1b1r/ppp2Bpp/1nn5/4k1B1/4N3/3P3P/PPP2PP1/R2bK2R w KQ - 0 13",
            M("f2f4", "f4+", "Intercale un échec décisif."),
            M("e5d4", "…Rd4", "La réplique adverse attendue."),
            M("a1d1", "Txd1", "Prends la pièce et lance la combinaison."),
            M("f8e7", "…Fe7", "La réplique adverse attendue."),
            M("e1f2", "Rf2", "Tends le piège en développant avec tempo."),
            M("e7g5", "…Fxg5", "L'adversaire mord à l'hameçon et capture !"),
            M("c2c3", "c3#", "Mat imparable !")),

        Trap(58, "Piège en Partie du pion dame ⚡", "Intermédiaire", "Défense", "Partie du pion dame", "black",
            "rnbqkbnr/ppp2pp1/8/3pB2p/3P4/4P3/PPP2PPP/RN1QKBNR b KQkq - 0 4",
            M("f7f6", "…f6", "Tends le piège en développant avec tempo."),
            M("e5f4", "Ff4", "La réplique adverse attendue."),
            M("g7g5", "…g5", "Tends le piège en développant avec tempo."),
            M("f4g3", "Fg3", "La réplique adverse attendue."),
            M("h5h4", "…h4", "Porte le coup de grâce tactique.")),

        Trap(59, "Piège en Partie du pion dame ⚡", "Intermédiaire", "Attaque", "Partie du pion dame", "white",
            "rnbq1rk1/pp2p1bp/2p5/3p1p1Q/3P1B2/2NBP3/PPP2PP1/R3K1N1 w Q - 0 10",
            M("g1f3", "Cf3", "Tends le piège en développant avec tempo."),
            M("d8e8", "…De8", "La réplique adverse attendue."),
            M("h5h2", "Dh2", "Tends le piège en développant avec tempo."),
            M("b8d7", "…Cd7", "La réplique adverse attendue."),
            M("e1c1", "O-O-O", "Tends le piège en développant avec tempo."),
            M("d7f6", "…Cf6", "La réplique adverse attendue."),
            M("d1h1", "Th1", "Porte le coup de grâce tactique.")),

        Trap(60, "Piège en Défense scandinave ⚡", "Intermédiaire", "Attaque", "Défense scandinave", "white",
            "rn1qkb1r/ppp1pppp/5n2/3p1b2/2P5/5NP1/PP1PPP1P/RNBQKB1R w KQkq - 1 4",
            M("c4d5", "cxd5", "Prends la pièce et lance la combinaison."),
            M("f6d5", "…Cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("e2e4", "e4", "Tends le piège en développant avec tempo."),
            M("f5e4", "…Fxe4", "L'adversaire mord à l'hameçon et capture !"),
            M("d1a4", "Da4+", "Échec et gain matériel décisif.")),

        Trap(61, "Piège en Ouverture Zukertort ⚡", "Intermédiaire", "Attaque", "Ouverture Zukertort", "white",
            "rn1qk2r/pbp1bppp/1p2pn2/8/4p3/3P1NP1/PPPN1PBP/R1BQ1RK1 w kq - 0 8",
            M("d3e4", "dxe4", "Prends la pièce et lance la combinaison."),
            M("f6e4", "…Cxe4", "L'adversaire mord à l'hameçon et capture !"),
            M("f3e5", "Ce5", "Tends le piège en développant avec tempo."),
            M("e4d6", "…Cd6", "La réplique adverse attendue."),
            M("g2b7", "Fxb7", "Prends la pièce et lance la combinaison."),
            M("d6b7", "…Cxb7", "L'adversaire mord à l'hameçon et capture !"),
            M("d1f3", "Df3", "Porte le coup de grâce tactique.")),

        Trap(62, "Piège en Ouverture anglaise ⚡", "Intermédiaire", "Défense", "Ouverture anglaise", "black",
            "r2qk1nr/pbpp1ppp/1p2p3/2n5/2P1P3/P1Q2N2/1P1P1PPP/R1B1KB1R b KQkq - 0 8",
            M("b7e4", "…Fxe4", "Prends la pièce et lance la combinaison."),
            M("c3g7", "Dxg7", "L'adversaire mord à l'hameçon et capture !"),
            M("d8f6", "…Df6", "Tends le piège en développant avec tempo."),
            M("g7f6", "Dxf6", "L'adversaire mord à l'hameçon et capture !"),
            M("g8f6", "…Cxf6", "Prends la pièce et lance la combinaison."),
            M("b2b4", "b4", "La réplique adverse attendue."),
            M("c5b3", "…Cb3", "Porte le coup de grâce tactique.")),

        Trap(63, "Piège en Attaque Trompowsky ⚡", "Intermédiaire", "Attaque", "Attaque Trompowsky", "white",
            "rn1qkb1r/ppp1pppp/5n2/3p1b2/3P1B2/4PP2/PPP3PP/RN1QKBNR w KQkq - 1 6",
            M("c2c4", "c4", "Tends le piège en développant avec tempo."),
            M("c7c5", "…c5", "La réplique adverse attendue."),
            M("c4d5", "cxd5", "Prends la pièce et lance la combinaison."),
            M("f6d5", "…Cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("f4b8", "Fxb8", "Prends la pièce et lance la combinaison."),
            M("a8b8", "…Txb8", "L'adversaire mord à l'hameçon et capture !"),
            M("e3e4", "e4", "Porte le coup de grâce tactique.")),

        Trap(64, "Piège en Défense mexicaine (Tango) ⚡", "Intermédiaire", "Défense", "Défense mexicaine (Tango)", "black",
            "r1bqk2r/pppp1ppp/6n1/2bPp3/2P1P1n1/2NB4/PP2NPPP/R1BQ1RK1 b kq - 6 8",
            M("d8h4", "…Dh4", "Tends le piège en développant avec tempo."),
            M("h2h3", "h3", "La réplique adverse attendue."),
            M("g4f2", "…Cxf2", "Prends la pièce et lance la combinaison."),
            M("f1f2", "Txf2", "L'adversaire mord à l'hameçon et capture !"),
            M("h4f2", "…Dxf2+", "Prends la pièce et lance la combinaison."),
            M("g1h1", "Rh1", "La réplique adverse attendue."),
            M("d7d6", "…d6", "Porte le coup de grâce tactique.")),

        Trap(65, "Piège en Défense française ⚡", "Intermédiaire", "Défense", "Défense française", "black",
            "r1bqkbnr/ppp3pp/2n1pp2/3pP3/3P1P2/2N5/PPP3PP/R1BQKBNR b KQkq - 0 5",
            M("f6e5", "…fxe5", "Prends la pièce et lance la combinaison."),
            M("f4e5", "fxe5", "L'adversaire mord à l'hameçon et capture !"),
            M("d8h4", "…Dh4+", "Intercale un échec décisif."),
            M("g2g3", "g3", "La réplique adverse attendue."),
            M("h4d4", "…Dxd4", "Capture la pièce sans défense !")),

        Trap(66, "Piège en Défense ouest-indienne ⚡", "Intermédiaire", "Défense", "Défense ouest-indienne", "black",
            "rn1qkb1r/pbpp1pp1/1p2pn1p/8/2PP3B/4PN2/PP3PPP/RN1QKB1R b KQkq - 1 6",
            M("f8b4", "…Fb4+", "Intercale un échec décisif."),
            M("b1d2", "Cbd2", "La réplique adverse attendue."),
            M("g7g5", "…g5", "Tends le piège en développant avec tempo."),
            M("h4g3", "Fg3", "La réplique adverse attendue."),
            M("g5g4", "…g4", "Tends le piège en développant avec tempo."),
            M("f3e5", "Ce5", "La réplique adverse attendue."),
            M("f6e4", "…Ce4", "Porte le coup de grâce tactique.")),

        Trap(67, "Piège en Défense française ⚡", "Intermédiaire", "Attaque", "Défense française", "white",
            "r2qkbnr/pppn1ppp/2b1p3/8/3PN3/3B1N2/PPP2PPP/R1BQK2R w KQkq - 5 7",
            M("d1e2", "De2", "Tends le piège en développant avec tempo."),
            M("g8f6", "…Cgf6", "La réplique adverse attendue."),
            M("e4f6", "Cxf6+", "Prends la pièce et lance la combinaison."),
            M("d8f6", "…Dxf6", "L'adversaire mord à l'hameçon et capture !"),
            M("c1g5", "Fg5", "Tends le piège en développant avec tempo."),
            M("c6f3", "…Fxf3", "L'adversaire mord à l'hameçon et capture !"),
            M("e2e3", "De3", "Porte le coup de grâce tactique.")),

        Trap(68, "Piège en Défense est-indienne ⚡", "Intermédiaire", "Attaque", "Défense est-indienne", "white",
            "r1bq1rk1/pp1nppb1/2pp1npp/6B1/2PP4/2N1PN2/PPQ1BPPP/R3K2R w KQ - 0 9",
            M("g5h4", "Fh4", "Tends le piège en développant avec tempo."),
            M("g6g5", "…g5", "La réplique adverse attendue."),
            M("h4g3", "Fg3", "Tends le piège en développant avec tempo."),
            M("f6h5", "…Ch5", "La réplique adverse attendue."),
            M("f3g5", "Cxg5", "Prends la pièce et lance la combinaison."),
            M("h6g5", "…hxg5", "L'adversaire mord à l'hameçon et capture !"),
            M("e2h5", "Fxh5", "Capture la pièce sans défense !")),

        Trap(69, "Piège en Défense hollandaise ⚡", "Intermédiaire", "Attaque", "Défense hollandaise", "white",
            "rnbq1knr/ppppp1b1/7p/7Q/3PPp2/8/PPP2PPP/RN2KBNR w KQ - 2 8",
            M("h5f5", "Df5+", "Intercale un échec décisif."),
            M("f8e8", "…Re8", "La réplique adverse attendue."),
            M("f1e2", "Fe2", "Tends le piège en développant avec tempo."),
            M("g8f6", "…Cf6", "La réplique adverse attendue."),
            M("e4e5", "e5", "Tends le piège en développant avec tempo."),
            M("f6d5", "…Cd5", "La réplique adverse attendue."),
            M("e2h5", "Fh5#", "Mat imparable !")),

        Trap(70, "Piège en Défense Caro-Kann ⚡", "Intermédiaire", "Attaque", "Défense Caro-Kann", "white",
            "r1bqkb1r/pp1n1ppp/2p1pn2/6N1/3P4/3B4/PPP2PPP/R1BQK1NR w KQkq - 0 7",
            M("g1f3", "C1f3", "Tends le piège en développant avec tempo."),
            M("h7h6", "…h6", "La réplique adverse attendue."),
            M("g5e6", "Cxe6", "Prends la pièce et lance la combinaison."),
            M("f7e6", "…fxe6", "L'adversaire mord à l'hameçon et capture !"),
            M("d3g6", "Fg6+", "Intercale un échec décisif."),
            M("e8e7", "…Re7", "La réplique adverse attendue."),
            M("e1g1", "O-O", "Porte le coup de grâce tactique.")),

        Trap(71, "Piège en Défense sicilienne ⚡", "Intermédiaire", "Attaque", "Défense sicilienne", "white",
            "r1bqkb1r/pp3ppp/2np1n2/1N2p3/4P3/2N5/PPP2PPP/R1BQKB1R w KQkq - 0 7",
            M("c3d5", "Cd5", "Tends le piège en développant avec tempo."),
            M("f6d5", "…Cxd5", "L'adversaire mord à l'hameçon et capture !"),
            M("e4d5", "exd5", "Prends la pièce et lance la combinaison."),
            M("c6e7", "…Ce7", "La réplique adverse attendue."),
            M("c2c4", "c4", "Tends le piège en développant avec tempo."),
            M("a7a6", "…a6", "La réplique adverse attendue."),
            M("d1a4", "Da4", "Porte le coup de grâce tactique.")),

        Trap(72, "Piège en Défense française ⚡", "Intermédiaire", "Attaque", "Défense française", "white",
            "r1b1kbnr/pp3ppp/1qn1p3/2ppP3/3P4/2P2N2/PP3PPP/RNBQKB1R w KQkq - 3 6",
            M("f1e2", "Fe2", "Tends le piège en développant avec tempo."),
            M("g8h6", "…Ch6", "La réplique adverse attendue."),
            M("c1h6", "Fxh6", "Prends la pièce et lance la combinaison."),
            M("b6b2", "…Dxb2", "L'adversaire mord à l'hameçon et capture !"),
            M("h6e3", "Fe3", "Tends le piège en développant avec tempo."),
            M("b2a1", "…Dxa1", "L'adversaire mord à l'hameçon et capture !"),
            M("d1c2", "Dc2", "Porte le coup de grâce tactique.")),

        Trap(73, "Piège en Partie viennoise ⚡", "Intermédiaire", "Attaque", "Partie viennoise", "white",
            "r1b2knr/pppp1ppp/2n5/2bNp3/2B1P1Q1/8/PPPP1qPP/R1BK2NR w - - 2 7",
            M("g1h3", "Ch3", "Tends le piège en développant avec tempo."),
            M("f2d4", "…Dd4", "La réplique adverse attendue."),
            M("d2d3", "d3", "Tends le piège en développant avec tempo."),
            M("d7d6", "…d6", "La réplique adverse attendue."),
            M("g4f3", "Df3", "Tends le piège en développant avec tempo."),
            M("c8h3", "…Fxh3", "L'adversaire mord à l'hameçon et capture !"),
            M("h1f1", "Tf1", "Porte le coup de grâce tactique.")),

        Trap(74, "Piège en Attaque Trompowsky ⚡", "Intermédiaire", "Défense", "Attaque Trompowsky", "black",
            "rnb1kb1r/pp1ppppp/1Q6/8/3pnB2/2P5/PP2PPPP/RN2KBNR b KQkq - 0 6",
            M("a7b6", "…axb6", "Prends la pièce et lance la combinaison."),
            M("f4b8", "Fxb8", "L'adversaire mord à l'hameçon et capture !"),
            M("d4c3", "…dxc3", "Prends la pièce et lance la combinaison."),
            M("b8e5", "Fe5", "La réplique adverse attendue."),
            M("a8a2", "…Txa2", "Prends la pièce et lance la combinaison."),
            M("a1a2", "Txa2", "L'adversaire mord à l'hameçon et capture !"),
            M("c3c2", "…c2", "Porte le coup de grâce tactique.")),

        Trap(75, "Piège en Gambit dame ⚡", "Intermédiaire", "Attaque", "Gambit dame", "white",
            "rnbqkb1r/5ppp/p3pn2/1pp5/2BP4/4PN2/PP2QPPP/RNB2RK1 w kq - 0 8",
            M("c4d3", "Fd3", "Tends le piège en développant avec tempo."),
            M("c8b7", "…Fb7", "La réplique adverse attendue."),
            M("d4c5", "dxc5", "Prends la pièce et lance la combinaison."),
            M("f8c5", "…Fxc5", "L'adversaire mord à l'hameçon et capture !"),
            M("d3b5", "Fxb5+", "Prends la pièce et lance la combinaison."),
            M("a6b5", "…axb5", "L'adversaire mord à l'hameçon et capture !"),
            M("e2b5", "Dxb5+", "Échec et gain matériel décisif.")),

        Trap(76, "Piège en Défense slave ⚡", "Intermédiaire", "Défense", "Défense slave", "black",
            "r2q1rk1/pp1n1ppp/2p1pn2/8/P2PP3/2PQ1N2/5PPP/R1B2RK1 b - - 0 12",
            M("d7c5", "…Cc5", "Tends le piège en développant avec tempo."),
            M("d3b1", "Db1", "La réplique adverse attendue."),
            M("c5e4", "…Ccxe4", "Prends la pièce et lance la combinaison."),
            M("b1b7", "Dxb7", "L'adversaire mord à l'hameçon et capture !"),
            M("d8b6", "…Db6", "Tends le piège en développant avec tempo."),
            M("b7b6", "Dxb6", "L'adversaire mord à l'hameçon et capture !"),
            M("a7b6", "…axb6", "Capture la pièce sans défense !")),

        Trap(77, "Piège en Partie du pion dame ⚡", "Intermédiaire", "Attaque", "Partie du pion dame", "white",
            "rn1qkbnr/ppp2ppp/4p3/3p1b2/3P1B2/4P3/PPP2PPP/RN1QKBNR w KQkq - 0 4",
            M("c2c4", "c4", "Tends le piège en développant avec tempo."),
            M("f5b1", "…Fxb1", "L'adversaire mord à l'hameçon et capture !"),
            M("a1b1", "Txb1", "Prends la pièce et lance la combinaison."),
            M("f8b4", "…Fb4+", "Échec intermédiaire adverse."),
            M("e1e2", "Re2", "Porte le coup de grâce tactique.")),

        Trap(78, "Piège en Partie du pion dame ⚡", "Intermédiaire", "Attaque", "Partie du pion dame", "white",
            "rnbqkb1r/ppp2ppp/4pn2/3p4/3P1B2/4P3/PPP2PPP/RN1QKBNR w KQkq - 0 4",
            M("g1f3", "Cf3", "Tends le piège en développant avec tempo."),
            M("c7c5", "…c5", "La réplique adverse attendue."),
            M("b1c3", "Cc3", "Tends le piège en développant avec tempo."),
            M("b8c6", "…Cc6", "La réplique adverse attendue."),
            M("c3b5", "Cb5", "Porte le coup de grâce tactique.")),

        Trap(79, "Piège en Défense Grünfeld ⚡", "Intermédiaire", "Défense", "Défense Grünfeld", "black",
            "r1bq1rk1/p1p1ppbp/1pn3p1/6B1/2BPP3/2P5/P3NPPP/R2Q1RK1 b - - 1 10",
            M("c8b7", "…Fb7", "Tends le piège en développant avec tempo."),
            M("d1d2", "Dd2", "La réplique adverse attendue."),
            M("d8d6", "…Dd6", "Tends le piège en développant avec tempo."),
            M("e4e5", "e5", "La réplique adverse attendue."),
            M("c6e5", "…Cxe5", "Prends la pièce et lance la combinaison."),
            M("d4e5", "dxe5", "L'adversaire mord à l'hameçon et capture !"),
            M("d6c6", "…Dc6", "Porte le coup de grâce tactique."))
    ];

    public TrainerCatalog()
    {
        foreach (var exercise in Exercises)
        {
            var board = BoardState.FromFen(exercise.InitialFen);
            foreach (var move in exercise.Moves)
            {
                board.Apply(move.Uci);
            }
        }
    }

    private static TrapMove M(string uci, string san, string hint) => new(uci, san, hint);

    private static TrapExercise Trap(
        int id,
        string title,
        string difficulty,
        string category,
        string opening,
        string color,
        string fen,
        params TrapMove[] moves) =>
        new(
            id,
            $"Piège {id} · {title}",
            title,
            difficulty,
            category,
            opening,
            color,
            id switch
            {
                15 => "Échecs atomiques",
                16 => "Roi de la colline",
                17 => "Échecs 960",
                _ => "Classique"
            },
            fen,
            moves);
}
